const errorHandler=async(req,res,next)=>{
console.log("custom error handler called");


}